### ISSUE TITLE
Location Issue

### ISSUE THREAD

**Issue by xvin1x** [Project-Sloth/ps-camera#12]
If you view the photo item at a different location, the location is changed each time. I believe this is because the location is based on player's current location

**Comment by xFutte** [comment]
Hey @xvin1x! I think the location issue is right. The solution is most likely just to save the location into the database and pull that when showing the picture. Is that something you could do a pull request on?

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-camera/pull/13

**Comment by xFutte** [comment]
Thanks.
