### ISSUE TITLE
Giving photo issue

### ISSUE THREAD

**Issue by jokernights** [Project-Sloth/ps-camera#28]
Everything works and takes great pictures, i can see the picture when I look at it, but if i give the picture to another player it puts a meme picture on it and when i get it back the original picture is gone. Fivemerr is setup properly as it does copy the correct picture and shows the proper picture in discord as well. It's only when you hand the picture to another player it breaks

**Comment by xFutte** [comment]
Looks like it the fallback value to KEK is because https://github.com/Project-Sloth/ps-camera/blob/398653cd6820b1104e986772413f21f17a121c26/client/nui/app.js#L81 open method's first argument is undefined.

**Comment by jokernights** [comment]
> Looks like it the fallback value to KEK is because
> 
> https://github.com/Project-Sloth/ps-camera/blob/398653cd6820b1104e986772413f21f17a121c26/client/nui/app.js#L81
> 
> image is undefined.

Sorry what does this mean? I did try a couple of prints as well and this is what i got. the first 2 with image and location is when i take the picture and the nil is when i hand it off to someone else.. Also the copy to clipboard doesn't work it says copied but doesn't actually copy the link?

![image](https://github.com/user-attachments/assets/f791f210-1dc7-4717-a4fb-5f8e6856088e)
![image](https://github.com/user-attachments/assets/19a7729d-c097-460d-a416-b831466ddba2)

**Comment by jokernights** [comment]
Any updates on this?

**Comment by rodrigofueda** [comment]
any news?????

**Comment by MonkeyWhisper** [comment]
Open source, fix it yourself.

**Comment by jokernights** [comment]
> Open source, fix it yourself.

You originally said you knew what the issue was In your discord and you were going to fix it and now it’s fix it yourself. Thankfully I had someone fix your broken code that you even admitted. You have one of the worse attitudes toward people it’s sickening. But then other days you are cool as shit. Thank god I quit fivem for now because some of the so called devs are very toxic and some are willing to lend a hand for someone to learn.  All you care about is the money from your servers that didn’t even work the greatest and you still blamed everyone else even if it was a you issue. Like when you changed my ip, said I never had the original ip when I had proof I did then admitted that your system changed the ip and still wouldn’t take the blame. Grow up and learn customer service.

**Comment by rodrigofueda** [comment]
Could you send the corrected code? I didn't find it in Discord

**Comment by jokernights** [comment]
> Could you send the corrected code? I didn't find it in Discord

I would have to remember what my friend did because I did shut my server down for now from the toxicity of a lot of the fivem devs and would have to go back through the code.

**Comment by rodrigofueda** [comment]
I understand :/ , in the past on an old server of mine it worked normally, now that I put it in it gives this error
