### ISSUE TITLE
Two things ive noticed playing with this

### ISSUE THREAD

**Issue by Nick5M420** [Project-Sloth/ps-camera#5]
1. When you cancel using the camera the frame overlay is still on the screen (untill you take a photo)

2. the "location" changes to wherever the player is looking at it

**Comment by Novalympous** [comment]
so with no 1 if you reuse the item it puts camera away and takes overlay away ive noticed that

**Comment by Nick5M420** [comment]
nice, any update on the second issue with the location reflecting back the current position you look at the photo kinda defeats the purpose of that

**Comment by MonkeyWhisper** [comment]
> nice, any update on the second issue with the location reflecting back the current position you look at the photo kinda defeats the purpose of that 
> 
> 

Annoying. 

Fix it yourself if you want or wait for us to work on it if we have time. 

Open source project, do it yourself.
