### ISSUE TITLE
Issue with minimap

### ISSUE THREAD

**Issue by lenzh** [Project-Sloth/ps-camera#8]
Minimap is displayed when as soon as taking a picture so its in the discord webhook

**Comment by MonkeyWhisper** [comment]
Issue with the pic location, thanks

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-camera/pull/13

**Comment by Smokiiee** [comment]
> 
@MonkeyWhisper 
after the update i still have map in the picture i take.
When i take the photo the map comes up for 2 sec and then disappears and comes back again when overlay is gone

**Comment by Smokiiee** [comment]
> > 
> 
> after the update i still have map in the picture i take. When i take the photo the map comes up for 2 sec and then disappears and comes back again when overlay is gone

https://streamable.com/tgax9w

**Comment by MonkeyWhisper** [comment]
> > 
> 
> @MonkeyWhisper after the update i still have map in the picture i take. When i take the photo the map comes up for 2 sec and then disappears and comes back again when overlay is gone

Okay, go ahead and fix it

**Comment by Smokiiee** [comment]
> > > 
> > 
> > 
> > @MonkeyWhisper after the update i still have map in the picture i take. When i take the photo the map comes up for 2 sec and then disappears and comes back again when overlay is gone
> 
> Okay, go ahead and fix it

I have tryied but not find out where

**Comment by Smokiiee** [comment]
> > > 
> > 
> > 
> > @MonkeyWhisper after the update i still have map in the picture i take. When i take the photo the map comes up for 2 sec and then disappears and comes back again when overlay is gone
> 
> Okay, go ahead and fix it

@MonkeyWhisper 

nvm i just fixed it. 

it was the local hook = grabWebhook() inside the elseif IsControlJustPressed(1, 176) then,
I just moved it up above  while camera and not IsEntityDead(lPed) and (GetVehiclePedIsIn(lPed) == vehicle) do
and it worked fine.

https://i.imgur.com/CUFESmr.png

**Comment by xFutte** [comment]
@Smokiiee Feel free to make a PR

**Comment by Smokiiee** [comment]
> @Smokiiee Feel free to make a PR

Its done 
#17
